apiVersion: apps/v1
kind: Deployment
metadata:
  name: threshold
spec:
  replicas: 1
  selector:
    matchLabels:
      name: threshold
  template:
    metadata:
      labels:
        name: threshold
    spec:
      containers:
        - name: threshold
          image: registry.cn-hangzhou.aliyuncs.com/limingmax-test/threshold:v2
          env:
          - name: REDIS_IP
            value: "192.168.195.1"
          - name: REDIS_PORT
            value: "30098"
          - name: KAFKA_IP
            value: "192.168.212.71"
          - name: KAFKA_PORT
            value: "9092"   
          - name: HBASE_IP
            value: "192.168.195.1"
          - name: HBASE_PORT
            value: "9090" 
          - name: CONSUMER_TOPIC
            value: "k8s_MonitorData" 
          - name: PRODUCER_TOPIC
            value: "ai_threshold_alert"  
          - name: MYSQL_IP
            value: "192.168.193.1"
          - name: MYSQL_PORT
            value: "30001"
          - name: MYSQL_USER
            value: "root"
          - name: MYSQL_PASSWD
            value: "123"
          - name: MYSQL_DB
            value: "notifies"            
          command: ['/bin/bash', '/service/threshold/src/start.sh']


